wget http://FungiDB.org/common/downloads/release-41/AkawachiiIFO4308/fasta/data/FungiDB-41_AkawachiiIFO4308_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AversicolorCBS583.65/fasta/data/FungiDB-41_AversicolorCBS583.65_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AsydowiiCBS593.65/fasta/data/FungiDB-41_AsydowiiCBS593.65_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PcinnamomiCBS144-22/fasta/data/FungiDB-41_PcinnamomiCBS144-22_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AwentiiDTO134E9/fasta/data/FungiDB-41_AwentiiDTO134E9_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AzonataCBS506.65/fasta/data/FungiDB-41_AzonataCBS506.65_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Foxysporum54006/fasta/data/FungiDB-41_Foxysporum54006_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Foxysporum26406/fasta/data/FungiDB-41_Foxysporum26406_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AluchuensisCBS106.47/fasta/data/FungiDB-41_AluchuensisCBS106.47_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/SdiclinaVS20/fasta/data/FungiDB-41_SdiclinaVS20_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AglaucusCBS516.65/fasta/data/FungiDB-41_AglaucusCBS516.65_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PjiroveciiSE8/fasta/data/FungiDB-41_PjiroveciiSE8_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PaphanidermatumDAOMBR444/fasta/data/FungiDB-41_PaphanidermatumDAOMBR444_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/ParrhenomanesATCC12531/fasta/data/FungiDB-41_ParrhenomanesATCC12531_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PirregulareDAOMBR486/fasta/data/FungiDB-41_PirregulareDAOMBR486_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PiwayamaiDAOMBR242034/fasta/data/FungiDB-41_PiwayamaiDAOMBR242034_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PultimumBR650/fasta/data/FungiDB-41_PultimumBR650_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PvexansDAOMBR484/fasta/data/FungiDB-41_PvexansDAOMBR484_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/FproliferatumET1/fasta/data/FungiDB-41_FproliferatumET1_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Foxysporumrace1/fasta/data/FungiDB-41_Foxysporumrace1_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Foxysporumrace4/fasta/data/FungiDB-41_Foxysporumrace4_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/FfujikuroiIMI58289/fasta/data/FungiDB-41_FfujikuroiIMI58289_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CgattiiEJB2/fasta/data/FungiDB-41_CgattiiEJB2_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CgattiiIND107/fasta/data/FungiDB-41_CgattiiIND107_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CgattiiNT10/fasta/data/FungiDB-41_CgattiiNT10_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CgattiiCA1873/fasta/data/FungiDB-41_CgattiiCA1873_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AcampestrisIBT28561/fasta/data/FungiDB-41_AcampestrisIBT28561_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AsteyniiIBT23096/fasta/data/FungiDB-41_AsteyniiIBT23096_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AnovofumigatusIBT16806/fasta/data/FungiDB-41_AnovofumigatusIBT16806_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AochraceoroseusIBT24754/fasta/data/FungiDB-41_AochraceoroseusIBT24754_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Sschenckii1099-18/fasta/data/FungiDB-41_Sschenckii1099-18_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Sbrasiliensis5110/fasta/data/FungiDB-41_Sbrasiliensis5110_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CneoformansJEC21/fasta/data/FungiDB-41_CneoformansJEC21_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiC735deltSOWgp/fasta/data/FungiDB-41_CposadasiiC735deltSOWgp_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AnidulansFGSCA4/fasta/data/FungiDB-41_AnidulansFGSCA4_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/FgraminearumPH-1/fasta/data/FungiDB-41_FgraminearumPH-1_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CneoformansH99/fasta/data/FungiDB-41_CneoformansH99_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CalbicansSC5314/fasta/data/FungiDB-41_CalbicansSC5314_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Umaydis521/fasta/data/FungiDB-41_Umaydis521_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Ccinereaokay7-130/fasta/data/FungiDB-41_Ccinereaokay7-130_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Moryzae70-15/fasta/data/FungiDB-41_Moryzae70-15_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/RdelemarRA99-880/fasta/data/FungiDB-41_RdelemarRA99-880_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CimmitisRS/fasta/data/FungiDB-41_CimmitisRS_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PchrysosporiumRP-78/fasta/data/FungiDB-41_PchrysosporiumRP-78_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CneoformansB-3501A/fasta/data/FungiDB-41_CneoformansB-3501A_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/YlipolyticaCLIB122/fasta/data/FungiDB-41_YlipolyticaCLIB122_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CglabrataCBS138/fasta/data/FungiDB-41_CglabrataCBS138_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Spombe972h/fasta/data/FungiDB-41_Spombe972h_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CalbicansWO1/fasta/data/FungiDB-41_CalbicansWO1_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CdeuterogattiiR265/fasta/data/FungiDB-41_CdeuterogattiiR265_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/ClusitaniaeATCC42720/fasta/data/FungiDB-41_ClusitaniaeATCC42720_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AfumigatusAf293/fasta/data/FungiDB-41_AfumigatusAf293_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AfischeriNRRL181/fasta/data/FungiDB-41_AfischeriNRRL181_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/BcinereaB05-10/fasta/data/FungiDB-41_BcinereaB05-10_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AflavusNRRL3357/fasta/data/FungiDB-41_AflavusNRRL3357_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Fverticillioides7600/fasta/data/FungiDB-41_Fverticillioides7600_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/ZtriticiIPO323/fasta/data/FungiDB-41_ZtriticiIPO323_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Ureesii1704/fasta/data/FungiDB-41_Ureesii1704_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/HcapsulatumNAm1/fasta/data/FungiDB-41_HcapsulatumNAm1_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AterreusNIH2624/fasta/data/FungiDB-41_AterreusNIH2624_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AclavatusNRRL1/fasta/data/FungiDB-41_AclavatusNRRL1_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/NcrassaOR74A/fasta/data/FungiDB-41_NcrassaOR74A_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CgattiiWM276/fasta/data/FungiDB-41_CgattiiWM276_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AnigerATCC1015/fasta/data/FungiDB-41_AnigerATCC1015_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CimmitisH538-4/fasta/data/FungiDB-41_CimmitisH538-4_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/SjaponicusyFS275/fasta/data/FungiDB-41_SjaponicusyFS275_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/BdendrobatidisJEL423/fasta/data/FungiDB-41_BdendrobatidisJEL423_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PinfestansT30-4/fasta/data/FungiDB-41_PinfestansT30-4_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CimmitisRMSCC2394/fasta/data/FungiDB-41_CimmitisRMSCC2394_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PgraminisCRL75-36-700-3/fasta/data/FungiDB-41_PgraminisCRL75-36-700-3_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AnigerCBS513-88/fasta/data/FungiDB-41_AnigerCBS513-88_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/MglobosaCBS7966/fasta/data/FungiDB-41_MglobosaCBS7966_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Foxysporum4287/fasta/data/FungiDB-41_Foxysporum4287_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/TreeseiQM6a/fasta/data/FungiDB-41_TreeseiQM6a_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PultimumDAOMBR144/fasta/data/FungiDB-41_PultimumDAOMBR144_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/TstipitatusATCC10500/fasta/data/FungiDB-41_TstipitatusATCC10500_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/TmarneffeiATCC18224/fasta/data/FungiDB-41_TmarneffeiATCC18224_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiSilveira/fasta/data/FungiDB-41_CposadasiiSilveira_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/HcapsulatumG186AR/fasta/data/FungiDB-41_HcapsulatumG186AR_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/HcapsulatumG217B/fasta/data/FungiDB-41_HcapsulatumG217B_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AfumigatusA1163/fasta/data/FungiDB-41_AfumigatusA1163_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiRMSCC3488/fasta/data/FungiDB-41_CposadasiiRMSCC3488_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CimmitisRMSCC3703/fasta/data/FungiDB-41_CimmitisRMSCC3703_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiRMSCC2133/fasta/data/FungiDB-41_CposadasiiRMSCC2133_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiRMSCC3700/fasta/data/FungiDB-41_CposadasiiRMSCC3700_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiCPA0001/fasta/data/FungiDB-41_CposadasiiCPA0001_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PbrasiliensisPb03/fasta/data/FungiDB-41_PbrasiliensisPb03_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/SoctosporusyFS286/fasta/data/FungiDB-41_SoctosporusyFS286_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiRMSCC1037/fasta/data/FungiDB-41_CposadasiiRMSCC1037_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiRMSCC1038/fasta/data/FungiDB-41_CposadasiiRMSCC1038_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiCPA0020/fasta/data/FungiDB-41_CposadasiiCPA0020_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CposadasiiCPA0066/fasta/data/FungiDB-41_CposadasiiCPA0066_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PrubensWisconsin54-1255/fasta/data/FungiDB-41_PrubensWisconsin54-1255_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PlutziiPb01/fasta/data/FungiDB-41_PlutziiPb01_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PbrasiliensisPb18/fasta/data/FungiDB-41_PbrasiliensisPb18_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AoryzaeRIB40/fasta/data/FungiDB-41_AoryzaeRIB40_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/NtetraspermaFGSC2508/fasta/data/FungiDB-41_NtetraspermaFGSC2508_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/NdiscretaFGSC8579/fasta/data/FungiDB-41_NdiscretaFGSC8579_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/HcapsulatumH88/fasta/data/FungiDB-41_HcapsulatumH88_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/HcapsulatumH143/fasta/data/FungiDB-41_HcapsulatumH143_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/ScerevisiaeS288c/fasta/data/FungiDB-41_ScerevisiaeS288c_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/HarabidopsidisEmoy2/fasta/data/FungiDB-41_HarabidopsidisEmoy2_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CparapsilosisCDC317/fasta/data/FungiDB-41_CparapsilosisCDC317_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/TmesentericaDSM1558/fasta/data/FungiDB-41_TmesentericaDSM1558_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AmacrogynusATCC38327/fasta/data/FungiDB-41_AmacrogynusATCC38327_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AcarbonariusITEM5010/fasta/data/FungiDB-41_AcarbonariusITEM5010_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/SpunctatusDAOMBR117/fasta/data/FungiDB-41_SpunctatusDAOMBR117_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/FoxysporumFo47/fasta/data/FungiDB-41_FoxysporumFo47_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Ssclerotiorum1980UF-70/fasta/data/FungiDB-41_Ssclerotiorum1980UF-70_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AaculeatusATCC16872/fasta/data/FungiDB-41_AaculeatusATCC16872_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/SparasiticaCBS223-65/fasta/data/FungiDB-41_SparasiticaCBS223-65_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Mlarici-populina98AG31/fasta/data/FungiDB-41_Mlarici-populina98AG31_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/McircinelloidesCBS277-49/fasta/data/FungiDB-41_McircinelloidesCBS277-49_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PparasiticaINRA-310/fasta/data/FungiDB-41_PparasiticaINRA-310_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PblakesleeanusNRRL1555/fasta/data/FungiDB-41_PblakesleeanusNRRL1555_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PcapsiciLT1534/fasta/data/FungiDB-41_PcapsiciLT1534_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AbrasiliensisCBS101740/fasta/data/FungiDB-41_AbrasiliensisCBS101740_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AtubingensisCBS134.48/fasta/data/FungiDB-41_AtubingensisCBS134.48_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Smacrosporak-hell/fasta/data/FungiDB-41_Smacrosporak-hell_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AlaibachiiNc14/fasta/data/FungiDB-41_AlaibachiiNc14_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/Acandida2VRR/fasta/data/FungiDB-41_Acandida2VRR_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/SreilianumSRZ2/fasta/data/FungiDB-41_SreilianumSRZ2_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AastaciAPO3/fasta/data/FungiDB-41_AastaciAPO3_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AinvadansNJM9701/fasta/data/FungiDB-41_AinvadansNJM9701_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/AnigerN402ATCC64974/fasta/data/FungiDB-41_AnigerN402ATCC64974_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CalbicansSC5314_B/fasta/data/FungiDB-41_CalbicansSC5314_B_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CaurisB8441/fasta/data/FungiDB-41_CaurisB8441_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/CneoformansKN99/fasta/data/FungiDB-41_CneoformansKN99_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/LprolificansJHH5317/fasta/data/FungiDB-41_LprolificansJHH5317_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/MoryzaeBR32/fasta/data/FungiDB-41_MoryzaeBR32_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PramorumPr-102/fasta/data/FungiDB-41_PramorumPr-102_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/PsojaeP6497/fasta/data/FungiDB-41_PsojaeP6497_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/SapiospermumIHEM14462/fasta/data/FungiDB-41_SapiospermumIHEM14462_Genome.fasta
wget http://FungiDB.org/common/downloads/release-41/YlipolyticaCLIB89W29/fasta/data/FungiDB-41_YlipolyticaCLIB89W29_Genome.fasta
