wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/dactylellina_haptotyla_cbs_200_50/dna/Dactylellina_haptotyla_cbs_200_50.MHA_v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/daedalea_quercina_l_15889/dna/Daedalea_quercina_l_15889.Daequ1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/debaryomyces_fabryi/dna/Debaryomyces_fabryi.debFab1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/debaryomyces_hansenii_cbs767/dna/Debaryomyces_hansenii_cbs767.ASM644v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/diaporthe_ampelina/dna/Diaporthe_ampelina.UCDDA912v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/diaporthe_helianthi/dna/Diaporthe_helianthi.ASM170239v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/dichomitus_squalens_lyad_421_ss1/dna/Dichomitus_squalens_lyad_421_ss1.Dichomitus_squalens_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/diplodia_corticola/dna/Diplodia_corticola.ASM188384v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/diplodia_seriata/dna/Diplodia_seriata.UCDDS831v0.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/diplodia_seriata_gca_001975905/dna/Diplodia_seriata_gca_001975905.Dipser_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/dothistroma_septosporum/dna/Dothistroma_septosporum.GCA_000340195.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/drechmeria_coniospora/dna/Drechmeria_coniospora.ASM162519v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/drechslerella_stenobrocha_248/dna/Drechslerella_stenobrocha_248.DREv1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/edhazardia_aedis_usnm_41457/dna/Edhazardia_aedis_usnm_41457.Edha_aedis_V4b.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/emergomyces_pasteuriana_ep9510/dna/Emergomyces_pasteuriana_ep9510.Emmo_past_UAMH9510_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/emmonsia_crescens_uamh_3008/dna/Emmonsia_crescens_uamh_3008.ASM100828v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/emmonsia_parva_uamh_139/dna/Emmonsia_parva_uamh_139.ASM101475v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/emmonsia_sp_cac_2015a/dna/Emmonsia_sp_cac_2015a.Emmo_afri_EA111.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/encephalitozoon_cuniculi_ecuniii_l/dna/Encephalitozoon_cuniculi_ecuniii_l.ECIIIL.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/encephalitozoon_cuniculi_gb_m1/dna/Encephalitozoon_cuniculi_gb_m1.ASM9122v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/encephalitozoon_hellem_atcc_50504/dna/Encephalitozoon_hellem_atcc_50504.ASM27781v3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/encephalitozoon_intestinalis_atcc_50506/dna/Encephalitozoon_intestinalis_atcc_50506.ASM14646v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/encephalitozoon_romaleae_sj_2008/dna/Encephalitozoon_romaleae_sj_2008.ASM28003v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/endocarpon_pusillum_z07020/dna/Endocarpon_pusillum_z07020.EPUS.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/enterocytozoon_bieneusi_h348/dna/Enterocytozoon_bieneusi_h348.ASM20948v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/enterocytozoon_hepatopenaei/dna/Enterocytozoon_hepatopenaei.ASM208167v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/enterospora_canceri/dna/Enterospora_canceri.ASM208791v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/eremothecium_cymbalariae_dbvpg_7215/dna/Eremothecium_cymbalariae_dbvpg_7215.ASM23536v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/eremothecium_gossypii_fdag1/dna/Eremothecium_gossypii_fdag1.ASM96883v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/eremothecium_sinecaudum/dna/Eremothecium_sinecaudum.ASM154855v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/erysiphe_necator/dna/Erysiphe_necator.ASM79871v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/escovopsis_weberi/dna/Escovopsis_weberi.ASM127849v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/eutypa_lata_ucrel1/dna/Eutypa_lata_ucrel1.UCREL1V03.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/exidia_glandulosa_hhb12029/dna/Exidia_glandulosa_hhb12029.Exigl1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/exophiala_aquamarina_cbs_119918/dna/Exophiala_aquamarina_cbs_119918.Exop_aqua_CBS_119918_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/exophiala_dermatitidis_nih_ut8656/dna/Exophiala_dermatitidis_nih_ut8656.Exop_derm_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/exophiala_mesophila/dna/Exophiala_mesophila.Exop_meso_CBS40295_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/exophiala_oligosperma/dna/Exophiala_oligosperma.Exop_olig_CBS72588_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/exophiala_sideris/dna/Exophiala_sideris.Exop_side_CBS121828_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/exophiala_spinifera/dna/Exophiala_spinifera.Exop_spin_CBS89968_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/exophiala_xenobiotica/dna/Exophiala_xenobiotica.Exop_xeno_CBS118157_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/fibroporia_radiculosa/dna/Fibroporia_radiculosa.ASM31352v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/fibulorhizoctonia_sp_cbs_109695/dna/Fibulorhizoctonia_sp_cbs_109695.Fibsp1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/fistulina_hepatica_atcc_64428/dna/Fistulina_hepatica_atcc_64428.Fishe1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/fomitiporia_mediterranea_mf3_22/dna/Fomitiporia_mediterranea_mf3_22.Fomme1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/fomitopsis_pinicola_fp_58527_ss1/dna/Fomitopsis_pinicola_fp_58527_ss1.Fompi3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fonsecaea_erecta/dna/Fonsecaea_erecta.ASM165198v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fonsecaea_monophora/dna/Fonsecaea_monophora.ASM164247v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fonsecaea_multimorphosa/dna/Fonsecaea_multimorphosa.ASM164698v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/fonsecaea_multimorphosa_cbs_102226/dna/Fonsecaea_multimorphosa_cbs_102226.Fons_mult_CBS_102226_V1.dna.toplevel.fa.gz 
