wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fonsecaea_nubica/dna/Fonsecaea_nubica.ASM164696v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/fonsecaea_pedrosoi_cbs_271_37/dna/Fonsecaea_pedrosoi_cbs_271_37.Fons_pedr_CBS_271_37_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fusarium_culmorum/dna/Fusarium_culmorum.EF1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fusarium_fujikuroi/dna/Fusarium_fujikuroi.EF1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/fusarium_fujikuroi_gca_001023035/dna/Fusarium_fujikuroi_gca_001023035.ASM102303v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fusarium_fujikuroi_gca_001023045/dna/Fusarium_fujikuroi_gca_001023045.ASM102304v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/fusarium_fujikuroi_gca_001023065/dna/Fusarium_fujikuroi_gca_001023065.ASM102306v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fusarium_graminearum/dna/Fusarium_graminearum.RR1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_graminearum_gca_000599445/dna/Fusarium_graminearum_gca_000599445.CS3005v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fusarium_langsethiae/dna/Fusarium_langsethiae.ASM129263v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fusarium_mangiferae/dna/Fusarium_mangiferae.Genome_assembly_version_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fusarium_oxysporum/dna/Fusarium_oxysporum.FO2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_conglutinans_race_2_54008/dna/Fusarium_oxysporum_f_sp_conglutinans_race_2_54008.FO_PHW808_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_cubense_race_1/dna/Fusarium_oxysporum_f_sp_cubense_race_1.Foc1_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_cubense_race_4/dna/Fusarium_oxysporum_f_sp_cubense_race_4.Foc4_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_cubense_tropical_race_4_54006/dna/Fusarium_oxysporum_f_sp_cubense_tropical_race_4_54006.FO_II5_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_lycopersici_mn25/dna/Fusarium_oxysporum_f_sp_lycopersici_mn25.FO_MN25_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_melonis_26406/dna/Fusarium_oxysporum_f_sp_melonis_26406.FO_melonis_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_pisi_hdv247/dna/Fusarium_oxysporum_f_sp_pisi_hdv247.FO_HDV247_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_radicis_lycopersici_26381/dna/Fusarium_oxysporum_f_sp_radicis_lycopersici_26381.FO_CL57_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_raphani_54005/dna/Fusarium_oxysporum_f_sp_raphani_54005.FO_PHW815_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_f_sp_vasinfectum_25433/dna/Fusarium_oxysporum_f_sp_vasinfectum_25433.FO_Cotton_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_fo47/dna/Fusarium_oxysporum_fo47.FO_Fo47_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/fusarium_oxysporum_fosc_3_a/dna/Fusarium_oxysporum_fosc_3_a.FO_FOSC_3_a_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fusarium_poae/dna/Fusarium_poae.FPOA1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fusarium_proliferatum/dna/Fusarium_proliferatum.F._proliferatum_NRRL62905_version_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/fusarium_proliferatum_et1/dna/Fusarium_proliferatum_et1.F._proliferatum_ET1_version_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fusarium_pseudograminearum/dna/Fusarium_pseudograminearum.GCA_000303195.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fusarium_solani/dna/Fusarium_solani.v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fusarium_verticillioides/dna/Fusarium_verticillioides.ASM14955v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/gaeumannomyces_graminis/dna/Gaeumannomyces_graminis.Gae_graminis_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/galerina_marginata_cbs_339_88/dna/Galerina_marginata_cbs_339_88.Galma1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/gelatoporia_subvermispora_b/dna/Gelatoporia_subvermispora_b.Ceriporiopsis_subvermispora_B_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/geotrichum_candidum/dna/Geotrichum_candidum.New2.3_08062011.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/glarea_lozoyensis_74030/dna/Glarea_lozoyensis_74030.LBAGla_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/glarea_lozoyensis_atcc_20868/dna/Glarea_lozoyensis_atcc_20868.GLAREA.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/gloeophyllum_trabeum_atcc_11539/dna/Gloeophyllum_trabeum_atcc_11539.Glotr1_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_chytridiomycota1_collection/gonapodya_prolifera_jel478/dna/Gonapodya_prolifera_jel478.Ganpr1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/grifola_frondosa/dna/Grifola_frondosa.ASM168373v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/grosmannia_clavigera_kw1407/dna/Grosmannia_clavigera_kw1407.Sanger-454-IlluminaPA_2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/gymnopus_luxurians_fd_317_m1/dna/Gymnopus_luxurians_fd_317_m1.Gymlu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/hanseniaspora_guilliermondii/dna/Hanseniaspora_guilliermondii.version_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/hanseniaspora_opuntiae/dna/Hanseniaspora_opuntiae.ASM174979v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/hanseniaspora_osmophila/dna/Hanseniaspora_osmophila.ASM174704v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/hanseniaspora_uvarum/dna/Hanseniaspora_uvarum.ASM174705v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/hanseniaspora_uvarum_dsm_2768/dna/Hanseniaspora_uvarum_dsm_2768.Huva2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/hanseniaspora_valbyensis_nrrl_y_1626/dna/Hanseniaspora_valbyensis_nrrl_y_1626.Hanva1_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/hebeloma_cylindrosporum_h7/dna/Hebeloma_cylindrosporum_h7.Hebeloma_cylindrosporum_h7_v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/hepatospora_eriocheir/dna/Hepatospora_eriocheir.ASM208787v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/hepatospora_eriocheir_gca_002087885/dna/Hepatospora_eriocheir_gca_002087885.ASM208788v1.dna.toplevel.fa.gz
