wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/heterobasidion_irregulare_tc_32_1/dna/Heterobasidion_irregulare_tc_32_1.Heterobasidion_irregulare_v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/hirsutella_minnesotensis_3608/dna/Hirsutella_minnesotensis_3608.ASM95604v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/histoplasma_capsulatum_g186ar/dna/Histoplasma_capsulatum_g186ar.ASM15011v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/histoplasma_capsulatum_h143/dna/Histoplasma_capsulatum_h143.ASM15103v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/histoplasma_capsulatum_h88/dna/Histoplasma_capsulatum_h88.ASM15100v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/histoplasma_capsulatum_nam1/dna/Histoplasma_capsulatum_nam1.ASM14958v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/hydnomerulius_pinastri_md_312/dna/Hydnomerulius_pinastri_md_312.Hydpi2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/hypholoma_sublateritium_fd_334_ss_4/dna/Hypholoma_sublateritium_fd_334_ss_4.Hypsu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/hyphopichia_burtonii_nrrl_y_1933/dna/Hyphopichia_burtonii_nrrl_y_1933.Hypbu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/hypsizygus_marmoreus/dna/Hypsizygus_marmoreus.ASM160531v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/isaria_fumosorosea_arsef_2679/dna/Isaria_fumosorosea_arsef_2679.ISF_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/jaapia_argillacea_mucl_33604/dna/Jaapia_argillacea_mucl_33604.Jaaar1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kalmanozyma_brasiliensis_ghg001/dna/Kalmanozyma_brasiliensis_ghg001.PSEUBRA1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/kazachstania_africana_cbs_2517/dna/Kazachstania_africana_cbs_2517.Ka_CBS2517.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/kazachstania_naganishii_cbs_8797/dna/Kazachstania_naganishii_cbs_8797.ASM34898v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/kluyveromyces_lactis/dna/Kluyveromyces_lactis.ASM251v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/kluyveromyces_marxianus/dna/Kluyveromyces_marxianus.KM1777_03.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/kluyveromyces_marxianus_dmku3_1042/dna/Kluyveromyces_marxianus_dmku3_1042.Kmar_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/komagataella_pastoris/dna/Komagataella_pastoris.GCA_000027005.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/komagataella_pastoris_gca_001708105/dna/Komagataella_pastoris_gca_001708105.ASM170810v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/komagataella_phaffii/dna/Komagataella_phaffii.ASM170808v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/komagataella_phaffii_cbs_7435/dna/Komagataella_phaffii_cbs_7435.PicPas_Mar2011.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/komagataella_phaffii_gs115/dna/Komagataella_phaffii_gs115.ASM174695v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/kuraishia_capsulata_cbs_1993/dna/Kuraishia_capsulata_cbs_1993.AUH_PRJEB4427_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kwoniella_bestiolae_cbs_10118/dna/Kwoniella_bestiolae_cbs_10118.Cryp_best_CBS10118_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kwoniella_dejecticola_cbs_10117/dna/Kwoniella_dejecticola_cbs_10117.Cryp_deje_CBS10117_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kwoniella_heveanensis_bcc8398/dna/Kwoniella_heveanensis_bcc8398.Cryp_heve_BCC8398_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kwoniella_heveanensis_cbs_569/dna/Kwoniella_heveanensis_cbs_569.Cryp_heve_CBS569_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kwoniella_mangroviensis_cbs_10435/dna/Kwoniella_mangroviensis_cbs_10435.Kwon_mang_CBS10435_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kwoniella_mangroviensis_cbs_8507/dna/Kwoniella_mangroviensis_cbs_8507.Kwon_mang_CBS8507_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kwoniella_mangroviensis_cbs_8886/dna/Kwoniella_mangroviensis_cbs_8886.Kwon_mang_CBS8886_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/kwoniella_pini_cbs_10737/dna/Kwoniella_pini_cbs_10737.Cryp_pinu_CBS10737_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/laccaria_amethystina_laam_08_1/dna/Laccaria_amethystina_laam_08_1.Laccaria_amethystina_LaAM-08-1_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/laccaria_bicolor_s238n_h82/dna/Laccaria_bicolor_s238n_h82.V1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/lachancea_dasiensis_cbs_10888/dna/Lachancea_dasiensis_cbs_10888.LADA0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/lachancea_fermentati/dna/Lachancea_fermentati.LAFE0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/lachancea_lanzarotensis/dna/Lachancea_lanzarotensis.LALA0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/lachancea_meyersii_cbs_8951/dna/Lachancea_meyersii_cbs_8951.LAME0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/lachancea_mirantina/dna/Lachancea_mirantina.LAMI0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/lachancea_nothofagi_cbs_11611/dna/Lachancea_nothofagi_cbs_11611.LANO0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/lachancea_sp_cbs_6924/dna/Lachancea_sp_cbs_6924.LAFA0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/lachancea_thermotolerans_cbs_6340/dna/Lachancea_thermotolerans_cbs_6340.ASM14280v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/laetiporus_sulphureus_93_53/dna/Laetiporus_sulphureus_93_53.Laesu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/lentinula_edodes/dna/Lentinula_edodes.Lened_assembly01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/leptosphaeria_maculans/dna/Leptosphaeria_maculans.ASM23037v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/leucoagaricus_sp_symc_cos/dna/Leucoagaricus_sp_symc_cos.ASM156373v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/lichtheimia_corymbifera_jmrc_fsu_9682/dna/Lichtheimia_corymbifera_jmrc_fsu_9682.454Minimus.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/lichtheimia_ramosa/dna/Lichtheimia_ramosa.Lramosa_hybrid_454_Illumina.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/lipomyces_starkeyi_nrrl_y_11557/dna/Lipomyces_starkeyi_nrrl_y_11557.Lipst1_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/lodderomyces_elongisporus_nrrl_yb_4239/dna/Lodderomyces_elongisporus_nrrl_yb_4239.ASM14968v1.dna.toplevel.fa.gz
