wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/macrophomina_phaseolina_ms6/dna/Macrophomina_phaseolina_ms6.MphMS6_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/madurella_mycetomatis/dna/Madurella_mycetomatis.ASM127576v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/magnaporthe_oryzae/dna/Magnaporthe_oryzae.MG8.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/magnaporthe_poae/dna/Magnaporthe_poae.Mag_poae_ATCC_64411_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/malassezia_pachydermatis/dna/Malassezia_pachydermatis.MalaPachy.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/malassezia_sympodialis_atcc_42132/dna/Malassezia_sympodialis_atcc_42132.ASM34930v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/malassezia_sympodialis_atcc_42132_gca_900149145/dna/Malassezia_sympodialis_atcc_42132_gca_900149145.Msy_ATCC_42132_Feb2016.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/marssonina_brunnea_f_sp_multigermtubi_mb_m1/dna/Marssonina_brunnea_f_sp_multigermtubi_mb_m1.ASM29877v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/melampsora_laricipopulina/dna/Melampsora_laricipopulina.GCA_000204055.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/metarhizium_acridum_cqma_102/dna/Metarhizium_acridum_cqma_102.MetAcr_May2010.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/metarhizium_album_arsef_1941/dna/Metarhizium_album_arsef_1941.MAM_1.0_for_version_1_of_the_Metarhizium_album_genome.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/metarhizium_anisopliae/dna/Metarhizium_anisopliae.Metarhizium_anisopliae.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/metarhizium_anisopliae_arsef_23/dna/Metarhizium_anisopliae_arsef_23.MAA_2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/metarhizium_anisopliae_arsef_549/dna/Metarhizium_anisopliae_arsef_549.MAN_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/metarhizium_anisopliae_brip_53284/dna/Metarhizium_anisopliae_brip_53284.ASM42698v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/metarhizium_anisopliae_brip_53293/dna/Metarhizium_anisopliae_brip_53293.ASM42696v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/metarhizium_brunneum_arsef_3297/dna/Metarhizium_brunneum_arsef_3297.MBR_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/metarhizium_guizhouense_arsef_977/dna/Metarhizium_guizhouense_arsef_977.MGU_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/metarhizium_majus_arsef_297/dna/Metarhizium_majus_arsef_297.MAJ_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/metarhizium_rileyi_rcef_4871/dna/Metarhizium_rileyi_rcef_4871.NOR_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/metarhizium_robertsii/dna/Metarhizium_robertsii.MR2010_11_27.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/metschnikowia_bicuspidata_var_bicuspidata_nrrl_yb_4993/dna/Metschnikowia_bicuspidata_var_bicuspidata_nrrl_yb_4993.Metbi1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/meyerozyma_guilliermondii_atcc_6260/dna/Meyerozyma_guilliermondii_atcc_6260.ASM14942v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/microbotryum_violaceum/dna/Microbotryum_violaceum.GCA_000166175.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/microdochium_bolleyi/dna/Microdochium_bolleyi.Microdochium_bolleyi_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/millerozyma_farinosa_cbs_7064/dna/Millerozyma_farinosa_cbs_7064.ASM31589v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/mitosporidium_daphniae/dna/Mitosporidium_daphniae.UGP1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/mixia_osmundae_iam_14324/dna/Mixia_osmundae_iam_14324.Mosmundae_2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/mixia_osmundae_iam_14324_gca_000708205/dna/Mixia_osmundae_iam_14324_gca_000708205.Mixia_osmundae_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/moesziomyces_antarcticus/dna/Moesziomyces_antarcticus.ASM74776v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/moesziomyces_aphidis_dsm_70725/dna/Moesziomyces_aphidis_dsm_70725.PseuAph1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/moniliophthora_perniciosa_fa553/dna/Moniliophthora_perniciosa_fa553.ASM18302v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/moniliophthora_roreri/dna/Moniliophthora_roreri.ASM146670v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/moniliophthora_roreri_mca_2997/dna/Moniliophthora_roreri_mca_2997.M_roreri_MCA_2997_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/mortierella_elongata_ag_77/dna/Mortierella_elongata_ag_77.Mortierella_elongata_AG-77_v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/mortierella_verticillata_nrrl_6337/dna/Mortierella_verticillata_nrrl_6337.Mort_vert_NRRL_6337_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/mucor_ambiguus/dna/Mucor_ambiguus.ASM95059v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/mucor_circinelloides_f_circinelloides_1006phl/dna/Mucor_circinelloides_f_circinelloides_1006phl.Muco_sp_1006Ph_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/mucor_circinelloides_f_lusitanicus_cbs_277_49/dna/Mucor_circinelloides_f_lusitanicus_cbs_277_49.Mucci2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/mycosphaerella_eumusae/dna/Mycosphaerella_eumusae.ASM157823v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/nadsonia_fulvescens_var_elongata_dsm_6958/dna/Nadsonia_fulvescens_var_elongata_dsm_6958.Nadfu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/nannizzia_gypsea_cbs_118893/dna/Nannizzia_gypsea_cbs_118893.MS_CBS118893.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/naumovozyma_castellii_cbs_4309/dna/Naumovozyma_castellii_cbs_4309.ASM23734v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/naumovozyma_dairenensis_cbs_421/dna/Naumovozyma_dairenensis_cbs_421.ASM22711v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nematocida_displodere/dna/Nematocida_displodere.ASM164239v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nematocida_parisii_ertm1/dna/Nematocida_parisii_ertm1.Nema_parisii_ERTm1_V3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nematocida_parisii_ertm3/dna/Nematocida_parisii_ertm3.Nema_parisii_ERTm3_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nematocida_sp_1_ertm2/dna/Nematocida_sp_1_ertm2.Nema_parisii_ERTm2_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nematocida_sp_1_ertm6/dna/Nematocida_sp_1_ertm6.Nema_sp_1_ERTm6_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nematocida_sp_ertm5/dna/Nematocida_sp_ertm5.ASM164241v1.dna.toplevel.fa.gz
