wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4513_fw_928_/dna/Pseudogymnoascus_sp_vkm_f_4513_fw_928_.DG7.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4514_fw_929_/dna/Pseudogymnoascus_sp_vkm_f_4514_fw_929_.DG8.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4515_fw_2607_/dna/Pseudogymnoascus_sp_vkm_f_4515_fw_2607_.DG10.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4516_fw_969_/dna/Pseudogymnoascus_sp_vkm_f_4516_fw_969_.DG11.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4517_fw_2822_/dna/Pseudogymnoascus_sp_vkm_f_4517_fw_2822_.DG13.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4518_fw_2643_/dna/Pseudogymnoascus_sp_vkm_f_4518_fw_2643_.DG36.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4519_fw_2642_/dna/Pseudogymnoascus_sp_vkm_f_4519_fw_2642_.DG38.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4520_fw_2644_/dna/Pseudogymnoascus_sp_vkm_f_4520_fw_2644_.DG39.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pseudogymnoascus_sp_wsf_3629/dna/Pseudogymnoascus_sp_wsf_3629.ASM166258v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pseudogymnoascus_verrucosus/dna/Pseudogymnoascus_verrucosus.ASM166265v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/pseudoloma_neurophilia/dna/Pseudoloma_neurophilia.ASM143216v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/pseudozyma_hubeiensis_sy62/dna/Pseudozyma_hubeiensis_sy62.ASM40351v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/puccinia_graminis/dna/Puccinia_graminis.ASM14992v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/puccinia_graminisug99/dna/Puccinia_graminisug99.v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/puccinia_sorghi/dna/Puccinia_sorghi.ASM126337v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/puccinia_striiformis/dna/Puccinia_striiformis.PST-130_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/puccinia_striiformis_f_sp_tritici_pst_78/dna/Puccinia_striiformis_f_sp_tritici_pst_78.P_striiformis_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/puccinia_triticina/dna/Puccinia_triticina.ASM15152v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/punctularia_strigosozonata_hhb_11173_ss5/dna/Punctularia_strigosozonata_hhb_11173_ss5.Punctularia_strigosozonata_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/purpureocillium_lilacinum/dna/Purpureocillium_lilacinum.ASM165320v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/purpureocillium_lilacinum_gca_001653265/dna/Purpureocillium_lilacinum_gca_001653265.ASM165326v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pyrenochaeta_sp_ds3say3a/dna/Pyrenochaeta_sp_ds3say3a.Pyrsp1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/pyrenophora_teres/dna/Pyrenophora_teres.GCA_000166005.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/pyrenophora_triticirepentis/dna/Pyrenophora_triticirepentis.ASM14998v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pyronema_omphalodes_cbs_100304/dna/Pyronema_omphalodes_cbs_100304.Pcon_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/rachicladosporium_antarcticum/dna/Rachicladosporium_antarcticum.ASM207706v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/rasamsonia_emersonii_cbs_393_64/dna/Rasamsonia_emersonii_cbs_393_64.ASM96859v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/rhinocladiella_mackenziei_cbs_650_93/dna/Rhinocladiella_mackenziei_cbs_650_93.Rhin_mack_CBS_650_93_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhizoctonia_solani/dna/Rhizoctonia_solani.AG22IIIB.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhizoctonia_solani_123e/dna/Rhizoctonia_solani_123e.Rhizoctonia_solani_123E_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhizoctonia_solani_ag_1_ia/dna/Rhizoctonia_solani_ag_1_ia.Rhisol_AG1IA_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhizoctonia_solani_ag_1_ib/dna/Rhizoctonia_solani_ag_1_ib.ASM35025v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhizoctonia_solani_ag_3_rhs1ap/dna/Rhizoctonia_solani_ag_3_rhs1ap.Rhizoctonia_solani_AG-3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhizoctonia_solani_ag_8_wac10335/dna/Rhizoctonia_solani_ag_8_wac10335.RSAG8-1.V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/rhizophagus_irregularis_daom_181602_gca_000439145/dna/Rhizophagus_irregularis_daom_181602_gca_000439145.Gloin1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/rhizophagus_irregularis_daom_197198w_gca_000597685/dna/Rhizophagus_irregularis_daom_197198w_gca_000597685.Rir.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhizopogon_vesiculosus/dna/Rhizopogon_vesiculosus.Rves_AM-OR11-056_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhizopogon_vinicolor_am_or11_026/dna/Rhizopogon_vinicolor_am_or11_026.Rhivi1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/rhizopus_delemar_ra_99_880/dna/Rhizopus_delemar_ra_99_880.RO3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/rhizopus_microsporus/dna/Rhizopus_microsporus.Rhimi_ATCC11559_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/rhizopus_microsporus_var_microsporus/dna/Rhizopus_microsporus_var_microsporus.Rhimi_ATCC52814_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhodotorula_graminis_wp1/dna/Rhodotorula_graminis_wp1.Rhoba1_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhodotorula_sp_jg_1b/dna/Rhodotorula_sp_jg_1b.Rhosp1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhodotorula_toruloides/dna/Rhodotorula_toruloides.IFO0880_HGAP3_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhodotorula_toruloides_atcc_204091/dna/Rhodotorula_toruloides_atcc_204091.R.glutinis2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/rhodotorula_toruloides_np11/dna/Rhodotorula_toruloides_np11.RHOziaDV1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/rhynchosporium_agropyri/dna/Rhynchosporium_agropyri.version_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/rhynchosporium_commune/dna/Rhynchosporium_commune.version_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/rhynchosporium_secalis/dna/Rhynchosporium_secalis.version_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_rozellomycota1_collection/rozella_allomycis_csf55/dna/Rozella_allomycis_csf55.Rozella_k41_t100.dna.toplevel.fa.gz
