wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_sydowii_cbs_593_65/dna/Aspergillus_sydowii_cbs_593_65.Aspsy1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/aspergillus_terreus/dna/Aspergillus_terreus.ASM14961v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_tubingensis_cbs_134_48/dna/Aspergillus_tubingensis_cbs_134_48.Asptu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_udagawae/dna/Aspergillus_udagawae.Aud_assembly01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/aspergillus_ustus/dna/Aspergillus_ustus.Austus1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_versicolor_cbs_583_65/dna/Aspergillus_versicolor_cbs_583_65.Aspve1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_wentii_dto_134e9/dna/Aspergillus_wentii_dto_134e9.Aspwe1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aureobasidium_melanogenum_cbs_110374/dna/Aureobasidium_melanogenum_cbs_110374.Aureobasidium_pullulans_var._melanogenum_CBS_110374_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aureobasidium_namibiae_cbs_147_97/dna/Aureobasidium_namibiae_cbs_147_97.Aureobasidium_pullulans_var._namibiae_CBS_147.97_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aureobasidium_pullulans/dna/Aureobasidium_pullulans.ASM167811v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aureobasidium_pullulans_exf_150/dna/Aureobasidium_pullulans_exf_150.Aureobasidium_pullulans_var._pullulans_EXF-150_assembly_version_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aureobasidium_subglaciale_exf_2481/dna/Aureobasidium_subglaciale_exf_2481.Aureobasidium_pullulans_var._subglaciale_EXF-2481_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/babjeviella_inositovora_nrrl_y_12698/dna/Babjeviella_inositovora_nrrl_y_12698.Babin1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_chytridiomycota1_collection/batrachochytrium_dendrobatidis_jam81/dna/Batrachochytrium_dendrobatidis_jam81.v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_chytridiomycota1_collection/batrachochytrium_dendrobatidis_jel423/dna/Batrachochytrium_dendrobatidis_jel423.BD_JEL423.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_chytridiomycota1_collection/batrachochytrium_salamandrivorans/dna/Batrachochytrium_salamandrivorans.Batr_sala_BS_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/baudoinia_panamericana_uamh_10762/dna/Baudoinia_panamericana_uamh_10762.Bauco1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/beauveria_bassiana/dna/Beauveria_bassiana.ASM168263v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/beauveria_bassiana_arsef_2860/dna/Beauveria_bassiana_arsef_2860.ASM28067v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/beauveria_bassiana_d1_5/dna/Beauveria_bassiana_d1_5.BBA1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/bipolaris_maydis_atcc_48331/dna/Bipolaris_maydis_atcc_48331.CocheC4_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/bipolaris_maydis_c5/dna/Bipolaris_maydis_c5.CocheC5_3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/bipolaris_oryzae_atcc_44560/dna/Bipolaris_oryzae_atcc_44560.Cochliobolus_miyabeanus_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/bipolaris_sorokiniana_nd90pr/dna/Bipolaris_sorokiniana_nd90pr.Cocsa1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/bipolaris_victoriae_fi3/dna/Bipolaris_victoriae_fi3.Cochliobolus_victoriae_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/bipolaris_zeicola_26_r_13/dna/Bipolaris_zeicola_26_r_13.Cochliobolus_carbonum_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/blastomyces_dermatitidis_atcc_18188/dna/Blastomyces_dermatitidis_atcc_18188.BD_ATCC18188_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/blastomyces_dermatitidis_atcc_26199/dna/Blastomyces_dermatitidis_atcc_26199.BD_ATCC26199_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/blastomyces_dermatitidis_er_3/dna/Blastomyces_dermatitidis_er_3.BD_ER3_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/blastomyces_gilchristii_slh14081/dna/Blastomyces_gilchristii_slh14081.BD_SLH14081_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/blastomyces_percursus/dna/Blastomyces_percursus.Blas_perc_EI222_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/blumeria_graminis/dna/Blumeria_graminis.EF2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/blumeria_graminis_f_sp_tritici_96224/dna/Blumeria_graminis_f_sp_tritici_96224.Bgt_454_newbler_assembly.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/botryobasidium_botryosum_fd_172_ss1/dna/Botryobasidium_botryosum_fd_172_ss1.Botbo1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/botrytis_cinerea/dna/Botrytis_cinerea.ASM83294v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/botrytis_cinerea_bcdw1/dna/Botrytis_cinerea_bcdw1.BcDW1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/botrytis_cinerea_t4/dna/Botrytis_cinerea_t4.BotFuc_Mar2011.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/brettanomyces_bruxellensis_awri1499/dna/Brettanomyces_bruxellensis_awri1499.AWRI1499_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/byssochlamys_spectabilis_no_5/dna/Byssochlamys_spectabilis_no_5.PVAR5_assembly01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/calocera_cornea_hhb12733/dna/Calocera_cornea_hhb12733.Calco1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/calocera_viscosa_tufc12733/dna/Calocera_viscosa_tufc12733.Calvi1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_12c/dna/Candida_albicans_12c.Cand_albi_12C_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_19f/dna/Candida_albicans_19f.Cand_albi_19F_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_ca6/dna/Candida_albicans_ca6.Cand_albi_Ca6_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_albicans_gc75/dna/Candida_albicans_gc75.Cand_albi_GC75_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_l26/dna/Candida_albicans_l26.Cand_albi_L26_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p34048/dna/Candida_albicans_p34048.Cand_albi_P34048_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_albicans_p37005/dna/Candida_albicans_p37005.Cand_albi_P37005_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_albicans_p37037/dna/Candida_albicans_p37037.Cand_albi_P37037_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p37039/dna/Candida_albicans_p37039.Cand_albi_P37039_V1.dna.toplevel.fa.gz    
