wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm683/dna/Saccharomyces_cerevisiae_yjm683.Sc_YJM683_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm689/dna/Saccharomyces_cerevisiae_yjm689.Sc_YJM689_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm693/dna/Saccharomyces_cerevisiae_yjm693.Sc_YJM693_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_yjm789/dna/Saccharomyces_cerevisiae_yjm789.ASM18143v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm969/dna/Saccharomyces_cerevisiae_yjm969.Sc_YJM969_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm972/dna/Saccharomyces_cerevisiae_yjm972.Sc_YJM972_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm975/dna/Saccharomyces_cerevisiae_yjm975.Sc_YJM975_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm978/dna/Saccharomyces_cerevisiae_yjm978.Sc_YJM978_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm981/dna/Saccharomyces_cerevisiae_yjm981.Sc_YJM981_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm984/dna/Saccharomyces_cerevisiae_yjm984.Sc_YJM984_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm987/dna/Saccharomyces_cerevisiae_yjm987.Sc_YJM987_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm990/dna/Saccharomyces_cerevisiae_yjm990.Sc_YJM990_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_yjm993/dna/Saccharomyces_cerevisiae_yjm993.Sc_YJM993_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm996/dna/Saccharomyces_cerevisiae_yjm996.Sc_YJM996_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_eubayanus/dna/Saccharomyces_eubayanus.SEUB3.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_kudriavzevii_ifo_1802/dna/Saccharomyces_kudriavzevii_ifo_1802.Saccharomyces_kudriavzevii_strain_IFO1802_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_sp_boulardii_/dna/Saccharomyces_sp_boulardii_.ASM129837v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_sp_boulardii__gca_001413975/dna/Saccharomyces_sp_boulardii__gca_001413975.ASM141397v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomycetaceae_sp_ashbya_aceri_/dna/Saccharomycetaceae_sp_ashbya_aceri_.ASM41222v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saitoella_complicata_nrrl_y_17804/dna/Saitoella_complicata_nrrl_y_17804.Scomplicata_3.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saitoella_complicata_nrrl_y_17804_gca_001661265/dna/Saitoella_complicata_nrrl_y_17804_gca_001661265.Saico1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/scedosporium_apiospermum/dna/Scedosporium_apiospermum.ScApio1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/scheffersomyces_stipitis_cbs_6054/dna/Scheffersomyces_stipitis_cbs_6054.ASM20916v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/schizophyllum_commune_h4_8/dna/Schizophyllum_commune_h4_8.v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/schizopora_paradoxa/dna/Schizopora_paradoxa.Schpa1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/schizosaccharomyces_cryophilus/dna/Schizosaccharomyces_cryophilus.GCA_000004155.2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/schizosaccharomyces_japonicus/dna/Schizosaccharomyces_japonicus.GCA_000149845.2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/schizosaccharomyces_octosporus/dna/Schizosaccharomyces_octosporus.GCA_000150505.2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/schizosaccharomyces_pombe/dna/Schizosaccharomyces_pombe.ASM294v2.dna_rm.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/scleroderma_citrinum_foug_a/dna/Scleroderma_citrinum_foug_a.Scleroderma_citrinum_Foug_A_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/sclerotinia_borealis_f_4128/dna/Sclerotinia_borealis_f_4128.SBOR_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/sclerotinia_sclerotiorum/dna/Sclerotinia_sclerotiorum.ASM14694v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/sclerotinia_sclerotiorum_1980_uf_70/dna/Sclerotinia_sclerotiorum_1980_uf_70.ASM185786v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/serendipita_indica_dsm_11827/dna/Serendipita_indica_dsm_11827.ASM31354v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/serendipita_vermifera_maff_305830/dna/Serendipita_vermifera_maff_305830.Sebacina_vermifera_MAFF_305830_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/serpula_lacrymans_var_lacrymans_s7_3/dna/Serpula_lacrymans_var_lacrymans_s7_3.v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/serpula_lacrymans_var_lacrymans_s7_9/dna/Serpula_lacrymans_var_lacrymans_s7_9.v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/setosphaeria_turcica_et28a/dna/Setosphaeria_turcica_et28a.Setospaeria_trucica_Et28A_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/sistotremastrum_niveocremeum_hhb9708/dna/Sistotremastrum_niveocremeum_hhb9708.Sisni1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/sistotremastrum_suecicum_hhb10207_ss_3/dna/Sistotremastrum_suecicum_hhb10207_ss_3.Sissu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/sordaria_macrospora/dna/Sordaria_macrospora.ASM18280v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/spathaspora_passalidarum_nrrl_y_27907/dna/Spathaspora_passalidarum_nrrl_y_27907.Spathaspora_passalidarum_v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/sphaerobolus_stellatus_ss14/dna/Sphaerobolus_stellatus_ss14.Sphst1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/sphaerulina_musiva_so2202/dna/Sphaerulina_musiva_so2202.Septoria_musiva_SO2202_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_chytridiomycota1_collection/spizellomyces_punctatus_daom_br117/dna/Spizellomyces_punctatus_daom_br117.S_punctatus_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/sporidiobolus_salmonicolor/dna/Sporidiobolus_salmonicolor.SPOSA68321A01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/sporisorium_reilianum/dna/Sporisorium_reilianum.GCA_000230245.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/sporisorium_scitamineum/dna/Sporisorium_scitamineum.Sporisorium_scitamineum.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/sporothrix_brasiliensis_5110/dna/Sporothrix_brasiliensis_5110.S_brasiliensis_5110_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/sporothrix_insectorum_rcef_264/dna/Sporothrix_insectorum_rcef_264.SPI_1.0.dna.toplevel.fa.gz
