wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/sporothrix_schenckii_1099_18/dna/Sporothrix_schenckii_1099_18.S_schenckii_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/sporothrix_schenckii_atcc_58251/dna/Sporothrix_schenckii_atcc_58251.Spor_sche_ATCC58251_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/spraguea_lophii_42_110/dna/Spraguea_lophii_42_110.Sprlop1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/stachybotrys_chartarum_ibt_40288/dna/Stachybotrys_chartarum_ibt_40288.S40288v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/stachybotrys_chartarum_ibt_40293/dna/Stachybotrys_chartarum_ibt_40293.S40293v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/stachybotrys_chartarum_ibt_7711/dna/Stachybotrys_chartarum_ibt_7711.S7711v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/stachybotrys_chlorohalonata_ibt_40285/dna/Stachybotrys_chlorohalonata_ibt_40285.S40285v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/stagonospora_sp_src1lsm3a/dna/Stagonospora_sp_src1lsm3a.Stasp1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/stemphylium_lycopersici/dna/Stemphylium_lycopersici.ASM119154v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/stereum_hirsutum_fp_91666_ss1/dna/Stereum_hirsutum_fp_91666_ss1.Stehi1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/sugiyamaella_lignohabitans/dna/Sugiyamaella_lignohabitans.ASM164002v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/suillus_luteus_uh_slu_lm8_n1/dna/Suillus_luteus_uh_slu_lm8_n1.Suilu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/talaromyces_cellulolyticus/dna/Talaromyces_cellulolyticus.TcelY94_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/talaromyces_islandicus/dna/Talaromyces_islandicus.PIS.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/talaromyces_marneffei_atcc_18224/dna/Talaromyces_marneffei_atcc_18224.JCVI-PMFA1-2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/talaromyces_marneffei_pm1/dna/Talaromyces_marneffei_pm1.ASM75011v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/talaromyces_stipitatus_atcc_10500/dna/Talaromyces_stipitatus_atcc_10500.JCVI-TSTA1-3.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/termitomyces_sp_j132/dna/Termitomyces_sp_j132.TerJ1321.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/tetrapisispora_blattae_cbs_6284/dna/Tetrapisispora_blattae_cbs_6284.ASM31591v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/tetrapisispora_phaffii_cbs_4417/dna/Tetrapisispora_phaffii_cbs_4417.ASM23690v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/thermothelomyces_thermophila_atcc_42464/dna/Thermothelomyces_thermophila_atcc_42464.ASM22609v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/thielavia_terrestris_nrrl_8126/dna/Thielavia_terrestris_nrrl_8126.ASM22611v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/thielaviopsis_punctulata/dna/Thielaviopsis_punctulata.ASM96861v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/tilletia_caries/dna/Tilletia_caries.ASM164500v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/tilletia_controversa/dna/Tilletia_controversa.ASM164504v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/tilletia_indica/dna/Tilletia_indica.ASM164501v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/tilletia_walkeri/dna/Tilletia_walkeri.ASM164505v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/tilletiaria_anomala_ubc_951/dna/Tilletiaria_anomala_ubc_951.Tilletiaria_anomala_UBC_951_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/tolypocladium_ophioglossoides_cbs_100239/dna/Tolypocladium_ophioglossoides_cbs_100239.Tophv1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/torrubiella_hemipterigena/dna/Torrubiella_hemipterigena.Allpaths-LG.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/tortispora_caseinolytica_nrrl_y_17796/dna/Tortispora_caseinolytica_nrrl_y_17796.Canca1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/torulaspora_delbrueckii/dna/Torulaspora_delbrueckii.ASM24337v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/trachipleistophora_hominis/dna/Trachipleistophora_hominis.ASM31613v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/trametes_cinnabarina/dna/Trametes_cinnabarina.BN946.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/trametes_pubescens/dna/Trametes_pubescens.ASM189594v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/trametes_versicolor_fp_101664_ss1/dna/Trametes_versicolor_fp_101664_ss1.Trametes_versicolor_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/tremella_mesenterica_dsm_1558/dna/Tremella_mesenterica_dsm_1558.Treme1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichoderma_atroviride_imi_206040/dna/Trichoderma_atroviride_imi_206040.TRIAT_v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/trichoderma_gamsii/dna/Trichoderma_gamsii.ASM148177v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/trichoderma_guizhouense/dna/Trichoderma_guizhouense.ASM202278v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/trichoderma_harzianum/dna/Trichoderma_harzianum.ASM98886v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/trichoderma_reesei/dna/Trichoderma_reesei.GCA_000167675.2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichoderma_reesei_rut_c_30/dna/Trichoderma_reesei_rut_c_30.TrireRUTC30_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/trichoderma_virens/dna/Trichoderma_virens.ASM17099v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_benhamiae_cbs_112371/dna/Trichophyton_benhamiae_cbs_112371.ASM15112v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_equinum_cbs_127_97/dna/Trichophyton_equinum_cbs_127_97.ASM15117v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_interdigitale_h6/dna/Trichophyton_interdigitale_h6.Tric_rubr_H6_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_interdigitale_mr816/dna/Trichophyton_interdigitale_mr816.Tric_inte_MR816_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/trichophyton_rubrum/dna/Trichophyton_rubrum.CMCC_F_T1i.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_cbs_100081/dna/Trichophyton_rubrum_cbs_100081.Tric_fish_CBS_100081_V1.dna.toplevel.fa.gz
