wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_cbs_118892/dna/Trichophyton_rubrum_cbs_118892.ASM15142v1.dna_sm.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_cbs_202_88/dna/Trichophyton_rubrum_cbs_202_88.Tric_raub_CBS_202_88_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_cbs_288_86/dna/Trichophyton_rubrum_cbs_288_86.Tric_fish_CBS_288_86_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_cbs_289_86/dna/Trichophyton_rubrum_cbs_289_86.Tric_kane_CBS_289_86_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_cbs_735_88/dna/Trichophyton_rubrum_cbs_735_88.Tric_megn_CBS_735_88_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_d6/dna/Trichophyton_rubrum_d6.Tric_rubr_D6_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_mr1448/dna/Trichophyton_rubrum_mr1448.Tric_rubr_M1448_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_mr1459/dna/Trichophyton_rubrum_mr1459.Tric_rubr_MR1459_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_rubrum_mr850/dna/Trichophyton_rubrum_mr850.Tric_rubr_MR-850_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_soudanense_cbs_452_61/dna/Trichophyton_soudanense_cbs_452_61.Tric_soud_CBS_452_61_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_tonsurans_cbs_112818/dna/Trichophyton_tonsurans_cbs_112818.ASM15145v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/trichophyton_verrucosum_hki_0517/dna/Trichophyton_verrucosum_hki_0517.ASM15150v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/trichophyton_violaceum/dna/Trichophyton_violaceum.CMCC_F_T3l.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/trichosporon_asahii_var_asahii_cbs_2479/dna/Trichosporon_asahii_var_asahii_cbs_2479.Trichosporon_asahii_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/trichosporon_asahii_var_asahii_cbs_8904/dna/Trichosporon_asahii_var_asahii_cbs_8904.ASM29921v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/tsuchiyaea_wingfieldii_cbs_7118/dna/Tsuchiyaea_wingfieldii_cbs_7118.Tsuc_wing_CBS7118_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/tuber_melanosporum/dna/Tuber_melanosporum.ASM15164v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/tulasnella_calospora_mut_4182/dna/Tulasnella_calospora_mut_4182.Tulasnella_calospora_AL13_4D_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/umbilicaria_pustulata/dna/Umbilicaria_pustulata.Lasallia_pustulata_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/uncinocarpus_reesii_1704/dna/Uncinocarpus_reesii_1704.ASM351v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/ustilaginoidea_virens/dna/Ustilaginoidea_virens.Assembly_for_version_1_of_the_Villosiclava_virens_genome.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/ustilaginoidea_virens_gca_000965225/dna/Ustilaginoidea_virens_gca_000965225.ASM96522v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/ustilago_bromivora/dna/Ustilago_bromivora.UBRO_v3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/ustilago_hordei/dna/Ustilago_hordei.ASM28603v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/ustilago_maydis/dna/Ustilago_maydis.Umaydis521_2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/valsa_mali/dna/Valsa_mali.ASM81815v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/valsa_mali_var_pyri/dna/Valsa_mali_var_pyri.ASM81338v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/vanderwaltozyma_polyspora_dsm_70294/dna/Vanderwaltozyma_polyspora_dsm_70294.ASM15003v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/vavraia_culicis_subsp_floridensis/dna/Vavraia_culicis_subsp_floridensis.Vavr_culi_floridensis_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/verruconis_gallopava/dna/Verruconis_gallopava.O_gall_CBS43764.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/verticillium_alfalfae_vams_102/dna/Verticillium_alfalfae_vams_102.ASM15082v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/verticillium_dahliae/dna/Verticillium_dahliae.ASM15067v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/verticillium_dahliaejr2/dna/Verticillium_dahliaejr2.VDAG_JR2v.4.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/verticillium_longisporum/dna/Verticillium_longisporum.vl2.denovo.v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/verticillium_longisporum_gca_001268145/dna/Verticillium_longisporum_gca_001268145.vl1.denovo.v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/vittaforma_corneae_atcc_50505/dna/Vittaforma_corneae_atcc_50505.Vitt_corn_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/wallemia_ichthyophaga_exf_994/dna/Wallemia_ichthyophaga_exf_994.Wallemia_ichthyophaga_version_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/wallemia_mellicola_cbs_633_66/dna/Wallemia_mellicola_cbs_633_66.Wallemia_sebi_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/wickerhamomyces_anomalus_nrrl_y_366_8/dna/Wickerhamomyces_anomalus_nrrl_y_366_8.Wican1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/wickerhamomyces_ciferrii/dna/Wickerhamomyces_ciferrii.ASM31348v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/xanthophyllomyces_dendrorhous/dna/Xanthophyllomyces_dendrorhous.Xden1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/xylona_heveae_tc161/dna/Xylona_heveae_tc161.Xylona_heveae_TC161_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/yarrowia_lipolytica/dna/Yarrowia_lipolytica.GCA_000002525.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/yarrowia_lipolytica_gca_001761485/dna/Yarrowia_lipolytica_gca_001761485.ASM176148v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/zygosaccharomyces_bailii_isa1307/dna/Zygosaccharomyces_bailii_isa1307.Z_bailii_ISA1307_version_3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/zygosaccharomyces_parabailii/dna/Zygosaccharomyces_parabailii.ASM198439v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/zygosaccharomyces_rouxii/dna/Zygosaccharomyces_rouxii.ASM2636v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/zygosaccharomyces_rouxii_gca_001972345/dna/Zygosaccharomyces_rouxii_gca_001972345.ZYGR_assembly01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/zymoseptoria_brevis/dna/Zymoseptoria_brevis.ASM96659v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/zymoseptoria_tritici/dna/Zymoseptoria_tritici.MG2.dna.toplevel.fa.gz
