mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/ashbya_gossypii/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/aspergillus_clavatus/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/aspergillus_flavus/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/aspergillus_fumigatus/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/aspergillus_fumigatusa1163/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/aspergillus_nidulans/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/aspergillus_niger/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/aspergillus_oryzae/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/aspergillus_terreus/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/beauveria_bassiana/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/blumeria_graminis/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/botrytis_cinerea/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/colletotrichum_gloeosporioides/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/colletotrichum_graminicola/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/colletotrichum_higginsianum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/colletotrichum_orbiculare/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/cryptococcus_neoformans/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/dothistroma_septosporum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fusarium_culmorum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fusarium_fujikuroi/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fusarium_graminearum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fusarium_oxysporum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fusarium_pseudograminearum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fusarium_solani/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fusarium_verticillioides/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/gaeumannomyces_graminis/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/komagataella_pastoris/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/leptosphaeria_maculans/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/magnaporthe_oryzae/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/magnaporthe_poae/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/melampsora_laricipopulina/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/microbotryum_violaceum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/neosartorya_fischeri/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/neurospora_crassa/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/phaeosphaeria_nodorum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/puccinia_graminis/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/puccinia_graminisug99/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/puccinia_striiformis/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/puccinia_triticina/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/pyrenophora_teres/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/pyrenophora_triticirepentis/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/saccharomyces_cerevisiae/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/schizosaccharomyces_cryophilus/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/schizosaccharomyces_japonicus/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/schizosaccharomyces_octosporus/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/schizosaccharomyces_pombe/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/sclerotinia_sclerotiorum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/sporisorium_reilianum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/trichoderma_reesei/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/trichoderma_virens/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/tuber_melanosporum/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/ustilago_maydis/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/verticillium_dahliae/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/verticillium_dahliaejr2/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/yarrowia_lipolytica/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/zymoseptoria_tritici/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_ascomycota1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_ascomycota2_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_ascomycota3_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_ascomycota4_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_basidiomycota1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_blastocladiomycota1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_chytridiomycota1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_entomophthoromycota1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_microsporidia1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_mucoromycota1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_neocallimastigomycota1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
mv ~/scratch/fungi/ensembl/newest_release/ftp.ensemblgenomes.org/pub/fungi/release-44/fasta/fungi_rozellomycota1_collection/*/dna/* ~/scratch/fungi/ensembl/single_files/release_44/
