wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/absidia_glauca/dna/Absidia_glauca.AG_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/acidomyces_richmondensis/dna/Acidomyces_richmondensis.ASM157207v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/acidomyces_richmondensis_bfw/dna/Acidomyces_richmondensis_bfw.Acidomyces_richmondensis_BFW_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/acremonium_chrysogenum_atcc_11550/dna/Acremonium_chrysogenum_atcc_11550.ASM76926v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/agaricus_bisporus_var_burnettii_jb137_s8/dna/Agaricus_bisporus_var_burnettii_jb137_s8.Agabi_varbur_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_blastocladiomycota1_collection/allomyces_macrogynus_atcc_38327/dna/Allomyces_macrogynus_atcc_38327.A_macrogynus_V3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/alternaria_alternata/dna/Alternaria_alternata.Altal1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/amanita_muscaria_koide_bx008/dna/Amanita_muscaria_koide_bx008.Amanita_muscaria_Koide_BX008_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/amphiamblys_sp_wsbs2006/dna/Amphiamblys_sp_wsbs2006.ASM187567v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/anncaliia_algerae_pra109/dna/Anncaliia_algerae_pra109.Annc_alge_PRA109_V4.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/anncaliia_algerae_pra339/dna/Anncaliia_algerae_pra339.Annc_alge_insect_USDA_JJB_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/anthracocystis_flocculosa_pf_1/dna/Anthracocystis_flocculosa_pf_1.Pflocc_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/arthrobotrys_oligospora_atcc_24927/dna/Arthrobotrys_oligospora_atcc_24927.AOL24927_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/arthroderma_otae_cbs_113480/dna/Arthroderma_otae_cbs_113480.ASM15114v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aschersonia_aleyrodis_rcef_2490/dna/Aschersonia_aleyrodis_rcef_2490.AAL_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/ascochyta_rabiei/dna/Ascochyta_rabiei.AscRab1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/ascoidea_rubescens_dsm_1968/dna/Ascoidea_rubescens_dsm_1968.Ascru1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/ascosphaera_apis_arsef_7405/dna/Ascosphaera_apis_arsef_7405.AAP_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/ashbya_gossypii/dna/Ashbya_gossypii.ASM9102v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_aculeatus_atcc_16872/dna/Aspergillus_aculeatus_atcc_16872.Aspac1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_bombycis/dna/Aspergillus_bombycis.ASM179269v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_brasiliensis_cbs_101740/dna/Aspergillus_brasiliensis_cbs_101740.Aspbr1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_calidoustus/dna/Aspergillus_calidoustus.Acal_Allpaths_LG.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_carbonarius_item_5010/dna/Aspergillus_carbonarius_item_5010.Aspca3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/aspergillus_clavatus/dna/Aspergillus_clavatus.ASM271v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_cristatus/dna/Aspergillus_cristatus.ASM171748v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/aspergillus_flavus/dna/Aspergillus_flavus.JCVI-afl1-v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/aspergillus_flavus_af70/dna/Aspergillus_flavus_af70.ASM95283v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/aspergillus_fumigatus/dna/Aspergillus_fumigatus.ASM265v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aspergillus_fumigatus_var_rp_2014/dna/Aspergillus_fumigatus_var_rp_2014.AspFumNiv1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_fumigatus_z5/dna/Aspergillus_fumigatus_z5.ASM102932v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/aspergillus_fumigatusa1163/dna/Aspergillus_fumigatusa1163.ASM15014v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_glaucus_cbs_516_65/dna/Aspergillus_glaucus_cbs_516_65.Aspgl1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_lentulus/dna/Aspergillus_lentulus.Alt_assembly01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_luchuensis/dna/Aspergillus_luchuensis.AspL_2604.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_luchuensis_cbs_106_47/dna/Aspergillus_luchuensis_cbs_106_47.Aspfo1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/aspergillus_nidulans/dna/Aspergillus_nidulans.ASM1142v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/aspergillus_nidulans_fgsc_a4/dna/Aspergillus_nidulans_fgsc_a4.ASM14920v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/aspergillus_niger/dna/Aspergillus_niger.ASM285v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aspergillus_niger_atcc_1015/dna/Aspergillus_niger_atcc_1015.ASPNI_v3.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_niger_gca_001515345/dna/Aspergillus_niger_gca_001515345.ASM151534v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_nomius_nrrl_13137/dna/Aspergillus_nomius_nrrl_13137.ASM120477v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/aspergillus_ochraceoroseus/dna/Aspergillus_ochraceoroseus.ASM98666v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/aspergillus_oryzae/dna/Aspergillus_oryzae.ASM18445v3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aspergillus_oryzae_100_8/dna/Aspergillus_oryzae_100_8.Aspergillus_oryzae_100-8.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aspergillus_oryzae_3_042/dna/Aspergillus_oryzae_3_042.AspOry3042.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_oryzae_gca_002007945/dna/Aspergillus_oryzae_gca_002007945.ASM200794v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/aspergillus_parasiticus_su_1/dna/Aspergillus_parasiticus_su_1.ASM95608v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/aspergillus_rambellii/dna/Aspergillus_rambellii.ASM98664v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/aspergillus_ruber_cbs_135680/dna/Aspergillus_ruber_cbs_135680.Eurhe1.dna.toplevel.fa.gz 
