wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p57055/dna/Candida_albicans_p57055.Cand_albi_P57055_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_albicans_p57072/dna/Candida_albicans_p57072.Cand_albi_P57072_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p60002/dna/Candida_albicans_p60002.Cand_albi_P60002_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p75010/dna/Candida_albicans_p75010.Cand_albi_P75010_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p75016/dna/Candida_albicans_p75016.Cand_albi_P75016_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p75063/dna/Candida_albicans_p75063.Cand_albi_P75063_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p76055/dna/Candida_albicans_p76055.Cand_albi_P76055_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p76067/dna/Candida_albicans_p76067.Cand_albi_P76067_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p78042/dna/Candida_albicans_p78042.Cand_albi_P78042_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_albicans_p78048/dna/Candida_albicans_p78048.Cand_albi_P78048_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p87/dna/Candida_albicans_p87.Cand_albi_P87_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_p94015/dna/Candida_albicans_p94015.Cand_albi_P94015_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_sc5314/dna/Candida_albicans_sc5314.Cand_albi_SC5314_V4.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/candida_albicans_sc5314_gca_000182965/dna/Candida_albicans_sc5314_gca_000182965.ASM18296v3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/candida_albicans_sc5314_gca_000784655/dna/Candida_albicans_sc5314_gca_000784655.Cand_albi_SC5314_V3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_albicans_wo_1/dna/Candida_albicans_wo_1.ASM14944v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/candida_arabinofermentans_nrrl_yb_2248/dna/Candida_arabinofermentans_nrrl_yb_2248.Canar1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_dubliniensis_cd36/dna/Candida_dubliniensis_cd36.ASM2694v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_maltosa_xu316/dna/Candida_maltosa_xu316.Cmaltosa_v01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_orthopsilosis_co_90_125/dna/Candida_orthopsilosis_co_90_125.ASM31587v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/candida_parapsilosis_cdc317/dna/Candida_parapsilosis_cdc317.ASM18276v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/candida_tanzawaensis_nrrl_y_17324/dna/Candida_tanzawaensis_nrrl_y_17324.Canta1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/candida_tropicalis_mya_3404/dna/Candida_tropicalis_mya_3404.ASM633v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/capronia_coronata_cbs_617_96/dna/Capronia_coronata_cbs_617_96.Capr_coro_CBS_617_96_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/capronia_epimyces_cbs_606_96/dna/Capronia_epimyces_cbs_606_96.Capr_epim_CBS_606_96_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/ceraceosorus_bombacis/dna/Ceraceosorus_bombacis.Ceraceosorus_bombacis.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/ceratocystis_platani/dna/Ceratocystis_platani.ASM97888v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/chaetomium_globosum_cbs_148_51/dna/Chaetomium_globosum_cbs_148_51.ASM14336v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/chaetomium_thermophilum_var_thermophilum_dsm_1495/dna/Chaetomium_thermophilum_var_thermophilum_dsm_1495.CTHT_3.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/choanephora_cucurbitarum/dna/Choanephora_cucurbitarum.ASM168372v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/cladophialophora_bantiana_cbs_173_52/dna/Cladophialophora_bantiana_cbs_173_52.Clad_bant_CBS_173_52_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/cladophialophora_carrionii/dna/Cladophialophora_carrionii.ASM170077v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/cladophialophora_carrionii_cbs_160_54/dna/Cladophialophora_carrionii_cbs_160_54.Clad_carr_CBS_160_54_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/cladophialophora_immunda/dna/Cladophialophora_immunda.Clad_immu_CBS83496_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/cladophialophora_psammophila_cbs_110553/dna/Cladophialophora_psammophila_cbs_110553.Clad_psam_CBS_110553_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/cladophialophora_yegresii_cbs_114405/dna/Cladophialophora_yegresii_cbs_114405.Clad_yegr_CBS_114405_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/claviceps_purpurea_20_1/dna/Claviceps_purpurea_20_1.ASM34735v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/clavispora_lusitaniae_atcc_42720/dna/Clavispora_lusitaniae_atcc_42720.ASM383v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/coccidioides_immitis_h538_4/dna/Coccidioides_immitis_h538_4.ASM14981v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/coccidioides_immitis_rmscc_2394/dna/Coccidioides_immitis_rmscc_2394.ASM14989v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/coccidioides_immitis_rmscc_3703/dna/Coccidioides_immitis_rmscc_3703.ASM15008v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/coccidioides_immitis_rs/dna/Coccidioides_immitis_rs.ASM14933v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/coccidioides_posadasii_c735_delta_sowgp/dna/Coccidioides_posadasii_c735_delta_sowgp.JCVI-cpa1-1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/coccidioides_posadasii_rmscc_3488/dna/Coccidioides_posadasii_rmscc_3488.ASM15005v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/coccidioides_posadasii_str_silveira/dna/Coccidioides_posadasii_str_silveira.CPS2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_chlorophyti/dna/Colletotrichum_chlorophyti.ASM193710v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/colletotrichum_fioriniae_pj7/dna/Colletotrichum_fioriniae_pj7.CFIO01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/colletotrichum_gloeosporioides/dna/Colletotrichum_gloeosporioides.GCA_000319635.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/colletotrichum_gloeosporioides_cg_14/dna/Colletotrichum_gloeosporioides_cg_14.Colletotrichum_gloeosporioides1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/colletotrichum_graminicola/dna/Colletotrichum_graminicola.C_graminicola_M1_001_V1.dna.toplevel.fa.gz
