wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/colletotrichum_higginsianum/dna/Colletotrichum_higginsianum.GCA_000313795.2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_higginsianum_imi_349063/dna/Colletotrichum_higginsianum_imi_349063.ASM167251v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_incanum/dna/Colletotrichum_incanum.Ci238704v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_incanum_gca_001855235/dna/Colletotrichum_incanum_gca_001855235.ASM185523v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_nymphaeae_sa_01/dna/Colletotrichum_nymphaeae_sa_01.CNYM01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/colletotrichum_orbiculare/dna/Colletotrichum_orbiculare.GCA_000350065.1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_orchidophilum/dna/Colletotrichum_orchidophilum.CORC01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_salicis/dna/Colletotrichum_salicis.CSAL01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_simmondsii/dna/Colletotrichum_simmondsii.CSIM01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/colletotrichum_sublineola/dna/Colletotrichum_sublineola.ASM69613v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/colletotrichum_tofieldiae/dna/Colletotrichum_tofieldiae.Ct0861v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_entomophthoromycota1_collection/conidiobolus_coronatus_nrrl_28638/dna/Conidiobolus_coronatus_nrrl_28638.Conidiobolus_coronatus_NRRL28638.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/coniochaeta_ligniaria_nrrl_30616/dna/Coniochaeta_ligniaria_nrrl_30616.Conlig_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/coniophora_puteana_rwd_64_598_ss2/dna/Coniophora_puteana_rwd_64_598_ss2.Conpu1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/coniosporium_apollinis_cbs_100218/dna/Coniosporium_apollinis_cbs_100218.Coni_apol_CBS100218_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/coprinopsis_cinerea_okayama7_130/dna/Coprinopsis_cinerea_okayama7_130.CC3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/cordyceps_brongniartii_rcef_3172/dna/Cordyceps_brongniartii_rcef_3172.BBO_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/cordyceps_confragosa/dna/Cordyceps_confragosa.ASM165321v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/cordyceps_confragosa_rcef_1005/dna/Cordyceps_confragosa_rcef_1005.LEL_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/cordyceps_militaris_cm01/dna/Cordyceps_militaris_cm01.CmilitarisCM01_v01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_amylolentus_cbs_6039/dna/Cryptococcus_amylolentus_cbs_6039.Cryp_amyl_CBS6039_V3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_amylolentus_cbs_6273/dna/Cryptococcus_amylolentus_cbs_6273.Cryp_amyl_CBS6273_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_depauperatus_cbs_7841/dna/Cryptococcus_depauperatus_cbs_7841.Filo_depa_CBS7841_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_depauperatus_cbs_7855/dna/Cryptococcus_depauperatus_cbs_7855.Filo_depa_CBS7855_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_ca1280/dna/Cryptococcus_gattii_ca1280.Cryp_gatt_CA1280_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_ca1873/dna/Cryptococcus_gattii_ca1873.Cryp_gatt_CA1873_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_e566/dna/Cryptococcus_gattii_e566.Cryp_gatt_E566_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_ejb2/dna/Cryptococcus_gattii_ejb2.Cryp_gatt_EJB2_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_nt_10/dna/Cryptococcus_gattii_nt_10.Cryp_gatt_NT-10_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_ru294/dna/Cryptococcus_gattii_ru294.Cryp_gatt_Ru294_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgii_2001_935_1/dna/Cryptococcus_gattii_vgii_2001_935_1.Cryp_gatt_2001_935-1_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgii_99_473/dna/Cryptococcus_gattii_vgii_99_473.Cryp_gatt_99_473_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgii_ca1014/dna/Cryptococcus_gattii_vgii_ca1014.Cryp_gatt_CA1014_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgii_cbs_10090/dna/Cryptococcus_gattii_vgii_cbs_10090.Cryp_gatt_CBS10090_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgii_la55/dna/Cryptococcus_gattii_vgii_la55.Cryp_gatt_LA55_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgii_mmrl2647/dna/Cryptococcus_gattii_vgii_mmrl2647.Cryp_gatt_MMRL2647_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgii_r265/dna/Cryptococcus_gattii_vgii_r265.CNB2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgii_ram5/dna/Cryptococcus_gattii_vgii_ram5.Cryp_gatt_Ram5_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_vgiv_ind107/dna/Cryptococcus_gattii_vgiv_ind107.Cryp_gatt_IND107_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_gattii_wm276/dna/Cryptococcus_gattii_wm276.ASM18594v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/cryptococcus_neoformans/dna/Cryptococcus_neoformans.ASM9104v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_neoformans_var_grubii_h99/dna/Cryptococcus_neoformans_var_grubii_h99.CNA3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cryptococcus_neoformans_var_neoformans_b_3501a/dna/Cryptococcus_neoformans_var_neoformans_b_3501a.ASM14938v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cutaneotrichosporon_oleaginosus/dna/Cutaneotrichosporon_oleaginosus.Triol1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/cyberlindnera_fabianii/dna/Cyberlindnera_fabianii.ASM198330v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/cyberlindnera_jadinii/dna/Cyberlindnera_jadinii.cj1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/cyberlindnera_jadinii_nrrl_y_1542/dna/Cyberlindnera_jadinii_nrrl_y_1542.Cybja1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/cylindrobasidium_torrendii_fp15055_ss_10/dna/Cylindrobasidium_torrendii_fp15055_ss_10.Cylto1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/cyphellophora_europaea_cbs_101466/dna/Cyphellophora_europaea_cbs_101466.Phia_euro_CBS_101466_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/dacryopinax_primogenitus/dna/Dacryopinax_primogenitus.Dacryopinax_sp._DJM_731_SSP1_v1.0.dna.toplevel.fa.gz   
