wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/neofusicoccum_parvum_ucrnp2/dna/Neofusicoccum_parvum_ucrnp2.UCRNP2V3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/neolecta_irregularis_dah_3/dna/Neolecta_irregularis_dah_3.NeoIirr1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/neolentinus_lepideus_hhb14362_ss_1/dna/Neolentinus_lepideus_hhb14362_ss_1.Neole1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/neonectria_ditissima/dna/Neonectria_ditissima.R0905_v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/neosartorya_fischeri/dna/Neosartorya_fischeri.ASM14964v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/neurospora_crassa/dna/Neurospora_crassa.NC12.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/neurospora_crassa_gca_000786625/dna/Neurospora_crassa_gca_000786625.Neucr_trp3_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/neurospora_tetrasperma_fgsc_2508/dna/Neurospora_tetrasperma_fgsc_2508.v2.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/neurospora_tetrasperma_fgsc_2509/dna/Neurospora_tetrasperma_fgsc_2509.v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nosema_apis_brl_01/dna/Nosema_apis_brl_01.NapisBRLv01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nosema_bombycis_cq1/dna/Nosema_bombycis_cq1.NosBomCQ1_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nosema_ceranae/dna/Nosema_ceranae.ASM98816v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/nosema_ceranae_brl01/dna/Nosema_ceranae_brl01.ASM18298v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/ogataea_parapolymorpha_dl_1/dna/Ogataea_parapolymorpha_dl_1.Hansenula_2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/ogataea_polymorpha/dna/Ogataea_polymorpha.Hanpo2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/oidiodendron_maius_zn/dna/Oidiodendron_maius_zn.Oidiodendron_maius_Zn_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/ophiocordyceps_sinensis_co18/dna/Ophiocordyceps_sinensis_co18.ASM44836v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/ophiocordyceps_unilateralis/dna/Ophiocordyceps_unilateralis.ASM127257v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/ophiostoma_piceae_uamh_11346/dna/Ophiostoma_piceae_uamh_11346.Opiceae_UAMHv01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_microsporidia1_collection/ordospora_colligata_oc4/dna/Ordospora_colligata_oc4.ASM80326v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pachysolen_tannophilus_nrrl_y_2460/dna/Pachysolen_tannophilus_nrrl_y_2460.Pacta1_2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/paracoccidioides_brasiliensis/dna/Paracoccidioides_brasiliensis.ASM171364v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/paracoccidioides_brasiliensis_gca_001713695/dna/Paracoccidioides_brasiliensis_gca_001713695.Paracocci_br_PbCNH.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/paracoccidioides_brasiliensis_pb03/dna/Paracoccidioides_brasiliensis_pb03.Paracocci_br_Pb03_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/paracoccidioides_brasiliensis_pb18/dna/Paracoccidioides_brasiliensis_pb18.Paracocci_br_Pb18_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/paracoccidioides_sp_lutzii_pb01/dna/Paracoccidioides_sp_lutzii_pb01.Paracocci_br_Pb01_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/paraphaeosphaeria_sporulosa/dna/Paraphaeosphaeria_sporulosa.Parsp1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/parasitella_parasitica/dna/Parasitella_parasitica.PP.v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/paxillus_involutus_atcc_200175/dna/Paxillus_involutus_atcc_200175.Paxillus_involutus_ATCC_200175_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/paxillus_rubicundulus_ve08_2h10/dna/Paxillus_rubicundulus_ve08_2h10.Paxillus_rubicundulus_Ve08.2h10_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicilliopsis_zonata_cbs_506_65/dna/Penicilliopsis_zonata_cbs_506_65.Aspzo1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_antarcticum/dna/Penicillium_antarcticum.ASM207234v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_arizonense/dna/Penicillium_arizonense.ASM177332v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/penicillium_brasilianum/dna/Penicillium_brasilianum.Pbras_Allpaths-LG.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_brasilianum_gca_002016555/dna/Penicillium_brasilianum_gca_002016555.ASM201655v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/penicillium_camemberti_fm_013/dna/Penicillium_camemberti_fm_013.PCAMFM013_20131106.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_chrysogenum/dna/Penicillium_chrysogenum.ASM71027v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_coprophilum/dna/Penicillium_coprophilum.ASM207240v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_decumbens/dna/Penicillium_decumbens.ASM207224v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_digitatum_pd1/dna/Penicillium_digitatum_pd1.PdigPd1_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_digitatum_phi26/dna/Penicillium_digitatum_phi26.PdigPHI26_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_expansum/dna/Penicillium_expansum.PEX1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_expansum_gca_000769735/dna/Penicillium_expansum_gca_000769735.ASM76973v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_expansum_gca_000769745/dna/Penicillium_expansum_gca_000769745.ASM76974v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_flavigenum/dna/Penicillium_flavigenum.ASM207236v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_freii/dna/Penicillium_freii.ASM151392v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_griseofulvum/dna/Penicillium_griseofulvum.ASM156193v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_italicum/dna/Penicillium_italicum.ASM76976v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_nalgiovense/dna/Penicillium_nalgiovense.ASM207242v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_nordicum/dna/Penicillium_nordicum.ASM127859v1.dna.toplevel.fa.gz
