wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_oxalicum_114_2/dna/Penicillium_oxalicum_114_2.pde_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_polonicum/dna/Penicillium_polonicum.ASM207226v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_roqueforti_fm164/dna/Penicillium_roqueforti_fm164.PROQFM164_20130607.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/penicillium_rubens_wisconsin_54_1255/dna/Penicillium_rubens_wisconsin_54_1255.PenChr_Nov2007.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_solitum/dna/Penicillium_solitum.ASM207223v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_steckii/dna/Penicillium_steckii.ASM207237v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_subrubescens/dna/Penicillium_subrubescens.ASM190812v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/penicillium_vulpinum/dna/Penicillium_vulpinum.ASM207225v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/peniophora_sp_cont/dna/Peniophora_sp_cont.Ricme1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/pestalotiopsis_fici_w106_1/dna/Pestalotiopsis_fici_w106_1.PFICI.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/phaeoacremonium_minimum_ucrpa7/dna/Phaeoacremonium_minimum_ucrpa7.UCRPA7V03.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/phaeomoniella_chlamydospora/dna/Phaeomoniella_chlamydospora.UCRPA7V1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/phaeosphaeria_nodorum/dna/Phaeosphaeria_nodorum.ASM14691v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/phanerochaete_carnosa_hhb_10118_sp/dna/Phanerochaete_carnosa_hhb_10118_sp.Phanerochaete_carnosa_HHB-10118-Sp_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/phialocephala_scopiformis/dna/Phialocephala_scopiformis.Phisc1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/phialocephala_subalpina/dna/Phialocephala_subalpina.PAC_version_1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/phialophora_americana/dna/Phialophora_americana.Capr_semi_CBS27337_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/phialophora_attae/dna/Phialophora_attae.ASM129925v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/phlebia_centrifuga/dna/Phlebia_centrifuga.ASM191385v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/phlebiopsis_gigantea_11061_1_cr5_6/dna/Phlebiopsis_gigantea_11061_1_cr5_6.Phlgi1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_mucoromycota1_collection/phycomyces_blakesleeanus_nrrl_1555_/dna/Phycomyces_blakesleeanus_nrrl_1555_.Phybl2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/pichia_kudriavzevii/dna/Pichia_kudriavzevii.ASM76445v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pichia_kudriavzevii_gca_001983325/dna/Pichia_kudriavzevii_gca_001983325.ASM198332v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pichia_membranifaciens/dna/Pichia_membranifaciens.P_membrenifaciens-1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pichia_membranifaciens_nrrl_y_2026/dna/Pichia_membranifaciens_nrrl_y_2026.Picme2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/piloderma_croceum_f_1598/dna/Piloderma_croceum_f_1598.Piloderma_croceum_F_1598_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/pisolithus_microcarpus_441/dna/Pisolithus_microcarpus_441.Pisolithus_microcarpus_441_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/pisolithus_tinctorius_marx_270/dna/Pisolithus_tinctorius_marx_270.Pisolithus_tinctorius_Marx_270_v1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/pleurotus_ostreatus_pc15/dna/Pleurotus_ostreatus_pc15.PleosPC15_2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/plicaturopsis_crispa_fd_325_ss_3/dna/Plicaturopsis_crispa_fd_325_ss_3.Plicr1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pneumocystis_carinii_b80/dna/Pneumocystis_carinii_b80.Pneu_cari_B80_V3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pneumocystis_jirovecii_ru7/dna/Pneumocystis_jirovecii_ru7.Pneu_jiro_RU7_V2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/pneumocystis_murina_b123/dna/Pneumocystis_murina_b123.Pneumo_murina_B123_V4.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pochonia_chlamydosporia_170/dna/Pochonia_chlamydosporia_170.ASM165323v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/podospora_anserina_s_mat_/dna/Podospora_anserina_s_mat_.ASM22654v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_basidiomycota1_collection/postia_placenta_mad_698_r/dna/Postia_placenta_mad_698_r.Postia_placenta_V1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/pseudocercospora_fijiensis_cirad86/dna/Pseudocercospora_fijiensis_cirad86.Mycfi2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pseudocercospora_musae/dna/Pseudocercospora_musae.ASM157822v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pseudogymnoascus_destructans/dna/Pseudogymnoascus_destructans.ASM164126v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/pseudogymnoascus_destructans_20631_21/dna/Pseudogymnoascus_destructans_20631_21.Geom_destructans_V1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pseudogymnoascus_sp_03vt05/dna/Pseudogymnoascus_sp_03vt05.ASM166264v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pseudogymnoascus_sp_05ny08/dna/Pseudogymnoascus_sp_05ny08.ASM166260v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pseudogymnoascus_sp_23342_1_i1/dna/Pseudogymnoascus_sp_23342_1_i1.ASM166257v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/pseudogymnoascus_sp_24mn13/dna/Pseudogymnoascus_sp_24mn13.ASM166259v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_103/dna/Pseudogymnoascus_sp_vkm_f_103.DG30.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/pseudogymnoascus_sp_vkm_f_3557/dna/Pseudogymnoascus_sp_vkm_f_3557.DG3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_3775/dna/Pseudogymnoascus_sp_vkm_f_3775.DG4.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/pseudogymnoascus_sp_vkm_f_3808/dna/Pseudogymnoascus_sp_vkm_f_3808.DG1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4246/dna/Pseudogymnoascus_sp_vkm_f_4246.DG5.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/pseudogymnoascus_sp_vkm_f_4281_fw_2241_/dna/Pseudogymnoascus_sp_vkm_f_4281_fw_2241_.DG6.dna.toplevel.fa.gz
