wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_arboricola_h_6/dna/Saccharomyces_arboricola_h_6.SacArb1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_awri796/dna/Saccharomyces_cerevisiae_awri796.ScAWRI796_v01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_cen_pk113_7d/dna/Saccharomyces_cerevisiae_cen_pk113_7d.ASM26988v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_ec1118/dna/Saccharomyces_cerevisiae_ec1118.ASM21897v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_fostersb/dna/Saccharomyces_cerevisiae_fostersb.ScFostersB_v01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_fosterso/dna/Saccharomyces_cerevisiae_fosterso.ScFostersO_v01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_gca_000091065/dna/Saccharomyces_cerevisiae_gca_000091065.ASM9106v2.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_gca_001634645/dna/Saccharomyces_cerevisiae_gca_001634645.GLBRCY22-3.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_gca_001983315/dna/Saccharomyces_cerevisiae_gca_001983315.ASM198331v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_kyokai_no_7/dna/Saccharomyces_cerevisiae_kyokai_no_7.K7_1.0.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_lalvin_qa23/dna/Saccharomyces_cerevisiae_lalvin_qa23.ScQA23_v01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_p283/dna/Saccharomyces_cerevisiae_p283.P283.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_p301/dna/Saccharomyces_cerevisiae_p301.p301.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_r008/dna/Saccharomyces_cerevisiae_r008.R008.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_r103/dna/Saccharomyces_cerevisiae_r103.R103.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_rm11_1a/dna/Saccharomyces_cerevisiae_rm11_1a.ASM14936v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_vin13/dna/Saccharomyces_cerevisiae_vin13.ScVIN13_v01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_vl3/dna/Saccharomyces_cerevisiae_vl3.ScVL3_v01.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota1_collection/saccharomyces_cerevisiae_x_saccharomyces_kudriavzevii_vin7/dna/Saccharomyces_cerevisiae_x_saccharomyces_kudriavzevii_vin7.ASM32610v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1078/dna/Saccharomyces_cerevisiae_yjm1078.Sc_YJM1078_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1083/dna/Saccharomyces_cerevisiae_yjm1083.Sc_YJM1083_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1129/dna/Saccharomyces_cerevisiae_yjm1129.Sc_YJM1129_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1133/dna/Saccharomyces_cerevisiae_yjm1133.Sc_YJM1133_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1190/dna/Saccharomyces_cerevisiae_yjm1190.Sc_YJM1190_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1199/dna/Saccharomyces_cerevisiae_yjm1199.Sc_YJM1199_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1202/dna/Saccharomyces_cerevisiae_yjm1202.Sc_YJM1202_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1208/dna/Saccharomyces_cerevisiae_yjm1208.Sc_YJM1208_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1242/dna/Saccharomyces_cerevisiae_yjm1242.Sc_YJM1242_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1244/dna/Saccharomyces_cerevisiae_yjm1244.Sc_YJM1244_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1248/dna/Saccharomyces_cerevisiae_yjm1248.Sc_YJM1248_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1250/dna/Saccharomyces_cerevisiae_yjm1250.Sc_YJM1250_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1252/dna/Saccharomyces_cerevisiae_yjm1252.Sc_YJM1252_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1273/dna/Saccharomyces_cerevisiae_yjm1273.Sc_YJM1273_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1304/dna/Saccharomyces_cerevisiae_yjm1304.Sc_YJM1304_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1307/dna/Saccharomyces_cerevisiae_yjm1307.Sc_YJM1307_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1311/dna/Saccharomyces_cerevisiae_yjm1311.Sc_YJM1311_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1326/dna/Saccharomyces_cerevisiae_yjm1326.Sc_YJM1326_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1332/dna/Saccharomyces_cerevisiae_yjm1332.Sc_YJM1332_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1336/dna/Saccharomyces_cerevisiae_yjm1336.Sc_YJM1336_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1338/dna/Saccharomyces_cerevisiae_yjm1338.Sc_YJM1338_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1341/dna/Saccharomyces_cerevisiae_yjm1341.Sc_YJM1341_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1342/dna/Saccharomyces_cerevisiae_yjm1342.Sc_YJM1342_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1355/dna/Saccharomyces_cerevisiae_yjm1355.Sc_YJM1355_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1356/dna/Saccharomyces_cerevisiae_yjm1356.Sc_YJM1356_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1381/dna/Saccharomyces_cerevisiae_yjm1381.Sc_YJM1381_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1383/dna/Saccharomyces_cerevisiae_yjm1383.Sc_YJM1383_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1385/dna/Saccharomyces_cerevisiae_yjm1385.Sc_YJM1385_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1386/dna/Saccharomyces_cerevisiae_yjm1386.Sc_YJM1386_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1387/dna/Saccharomyces_cerevisiae_yjm1387.Sc_YJM1387_v1.dna.toplevel.fa.gz
