wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1388/dna/Saccharomyces_cerevisiae_yjm1388.Sc_YJM1388_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1389/dna/Saccharomyces_cerevisiae_yjm1389.Sc_YJM1389_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1399/dna/Saccharomyces_cerevisiae_yjm1399.Sc_YJM1399_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1400/dna/Saccharomyces_cerevisiae_yjm1400.Sc_YJM1400_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1401/dna/Saccharomyces_cerevisiae_yjm1401.Sc_YJM1401_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1402/dna/Saccharomyces_cerevisiae_yjm1402.Sc_YJM1402_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1415/dna/Saccharomyces_cerevisiae_yjm1415.Sc_YJM1415_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1417/dna/Saccharomyces_cerevisiae_yjm1417.Sc_YJM1417_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1418/dna/Saccharomyces_cerevisiae_yjm1418.Sc_YJM1418_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1419/dna/Saccharomyces_cerevisiae_yjm1419.Sc_YJM1419_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1433/dna/Saccharomyces_cerevisiae_yjm1433.Sc_YJM1433_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1434/dna/Saccharomyces_cerevisiae_yjm1434.Sc_YJM1434_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1439/dna/Saccharomyces_cerevisiae_yjm1439.Sc_YJM1439_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1443/dna/Saccharomyces_cerevisiae_yjm1443.Sc_YJM1443_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1444/dna/Saccharomyces_cerevisiae_yjm1444.Sc_YJM1444_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1447/dna/Saccharomyces_cerevisiae_yjm1447.Sc_YJM1447_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1450/dna/Saccharomyces_cerevisiae_yjm1450.Sc_YJM1450_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1460/dna/Saccharomyces_cerevisiae_yjm1460.Sc_YJM1460_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1463/dna/Saccharomyces_cerevisiae_yjm1463.Sc_YJM1463_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1477/dna/Saccharomyces_cerevisiae_yjm1477.Sc_YJM1477_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1478/dna/Saccharomyces_cerevisiae_yjm1478.Sc_YJM1478_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1479/dna/Saccharomyces_cerevisiae_yjm1479.Sc_YJM1479_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1526/dna/Saccharomyces_cerevisiae_yjm1526.Sc_YJM1526_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1527/dna/Saccharomyces_cerevisiae_yjm1527.Sc_YJM1527_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1549/dna/Saccharomyces_cerevisiae_yjm1549.Sc_YJM1549_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1573/dna/Saccharomyces_cerevisiae_yjm1573.Sc_YJM1573_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1574/dna/Saccharomyces_cerevisiae_yjm1574.Sc_YJM1574_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm1592/dna/Saccharomyces_cerevisiae_yjm1592.Sc_YJM1592_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm1615/dna/Saccharomyces_cerevisiae_yjm1615.Sc_YJM1615_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm189/dna/Saccharomyces_cerevisiae_yjm189.Sc_YJM189_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm193/dna/Saccharomyces_cerevisiae_yjm193.Sc_YJM193_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm195/dna/Saccharomyces_cerevisiae_yjm195.Sc_YJM195_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm244/dna/Saccharomyces_cerevisiae_yjm244.Sc_YJM244_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm248/dna/Saccharomyces_cerevisiae_yjm248.Sc_YJM248_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm270/dna/Saccharomyces_cerevisiae_yjm270.Sc_YJM270_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm271/dna/Saccharomyces_cerevisiae_yjm271.Sc_YJM271_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota3_collection/saccharomyces_cerevisiae_yjm320/dna/Saccharomyces_cerevisiae_yjm320.Sc_YJM320_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm326/dna/Saccharomyces_cerevisiae_yjm326.Sc_YJM326_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm428/dna/Saccharomyces_cerevisiae_yjm428.Sc_YJM428_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm450/dna/Saccharomyces_cerevisiae_yjm450.Sc_YJM450_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm451/dna/Saccharomyces_cerevisiae_yjm451.Sc_YJM451_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm453/dna/Saccharomyces_cerevisiae_yjm453.Sc_YJM453_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm456/dna/Saccharomyces_cerevisiae_yjm456.Sc_YJM456_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm470/dna/Saccharomyces_cerevisiae_yjm470.Sc_YJM470_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm541/dna/Saccharomyces_cerevisiae_yjm541.Sc_YJM541_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm554/dna/Saccharomyces_cerevisiae_yjm554.Sc_YJM554_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm555/dna/Saccharomyces_cerevisiae_yjm555.Sc_YJM555_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm627/dna/Saccharomyces_cerevisiae_yjm627.Sc_YJM627_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm681/dna/Saccharomyces_cerevisiae_yjm681.Sc_YJM681_v1.dna.toplevel.fa.gz
wget ftp://ftp.ensemblgenomes.org/pub/release-39/fungi/fasta/fungi_ascomycota2_collection/saccharomyces_cerevisiae_yjm682/dna/Saccharomyces_cerevisiae_yjm682.Sc_YJM682_v1.dna.toplevel.fa.gz
